# Simplest role possible for extracting previously backed up JENKINS_HOME
#folder to our Jenkins server.
- name: Stop service Jenkins, if started
  service:
    name: jenkins
    state: stopped
  become: yes

- name: Restore Jenkins initial configuration
  become: yes
  unarchive:
    src: "../files/jenkins.tar.gz"
    dest: /var/lib/jenkins/

- name: Start Jenkins service
  service:
    name: jenkins
    state: started
  become: yes

# Create a Jenkins job using basic authentication
#- jenkins_job:
#    config: "{{ lookup('file', 'templates/test-01.xml') }}"
#    name: test-01
#    password: admin
#    url: http://server-03
#    user: admin
