#This Role adds jobs to Jenkins
- name: Install Dependencies
  apt:
    update_cache: yes
    name: ['python-jenkins','python-pip']
    state: present
  become: yes

- name: Install lxml using pip
  command: pip install lxml

# Create a jenkins job using the token
- jenkins_job:
    config: "{{ lookup('template', '../templates/eShop-update.xml') }}"
    name: eShop-update-created-with-Ansible
    state: present
    token: 11788f22dcc6d3d424724137b83e3f935e
    url: http://localhost:8080
    user: admin
