---
- name: "Delete the old database"
  mysql_db:
    name: "{{ wp_db_name }}"
    state: "absent"
    login_password: "{{ mysql_root_password }}"
    login_user: "root"

- name: "Restore the database"
  mysql_db:
    name: "{{ wp_db_name }}"
    state: "import"
    target: "/vagrant/{{ wp_db_filename }}.sql"
    login_password: "{{ mysql_root_password }}"
    login_user: "root"
