---
- name: "Delete the old database"
  mysql_db:
    name: "{{ wp_db_name }}"
    state: "absent"
    login_password: "{{ mysql_root_password }}"
    login_user: "root"

#- name: "Restore the database"
#  mysql_db:
#    name: "{{ wp_db_name }}"
#    state: "import"
#    target: "../{{ wp_db_filename }}.sql"
#    login_password: "{{ mysql_root_password }}"
#    login_user: "root"


- name: "Copy database dump file and restore the database"
  copy:
    src: "../files/{{ wp_db_filename }}.sql"
    dest: /tmp

- name: "Restore the database"
  mysql_db:
    name: "{{ wp_db_name }}"
    state: "import"
    target: "/tmp/{{ wp_db_filename }}.sql"
    login_password: "{{ mysql_root_password }}"
    login_user: "root"

- name: "Delete dumpfile"
  file:
    path: "/tmp/{{ wp_db_filename }}.sql"
    state: absent
